controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanumbot_drive_controller:
      type: mecanumbot_controller/MecanumbotDriveController

mecanumbot_drive_controller:
  ros__parameters:
    r_wheel_joint_name: r_wheel_joint
    l_wheel_joint_name: l_wheel_joint
    wheel_radius: 0.03
    wheel_distance:
      width: 0.46
      length: 0.40